stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./data/Dockerfile
      buildContext: ./data
      tag: data:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
